---
title: 'Homework 6'
author: "STA-360"
output: pdf_document
indent: true
documentclass: article
---

Total points: 10 (reproducibility) + 0 (Q1) + 20 (Q2)\

**General instructions for homeworks**: Please follow the uploading file instructions according to the syllabus. You will give the commands to answer each question in its own code block, which will also produce plots that will be automatically embedded in the output file. Each answer must be supported by written statements as well as any code used. Your code must be completely reproducible and must compile. 

**Advice**: Start early on the homeworks and it is advised that you not wait until the day of. While the professor and the TA's check emails, they will be answered in the order they are received and last minute help will not be given unless we happen to be free.  

**Commenting code**
Code should be commented. See the Google style guide for questions regarding commenting or how to write 
code \url{https://google.github.io/styleguide/Rguide.xml}. No late homework's will be accepted.

1. *Lab component* Refer to lab 6 (**Gibbs sampling, Module 7, Part I**) and complete tasks 4-5. **This will not be graded, but you will be expected to know this for the exam.**
  
2. *Censored Gibbs sampling* (20 points) Please complete the censored **Gibbs sampling problem from Module 7, Part II**. You may assume that $a=1,b=1, r=10.$ You may use any code that was given to you in class or you may choose to write your own code. If you use the code from class, please cite and reference this.

(a) (5 points) Write code to produce trace plots and running average plots for the censored values for 200 iterations. Do these diagnostic plots suggest that you have run the sampler long enough? Explain. 

(b) (5 points) Now run the chain for 10,000 iterations  and update your diagnostic plots (traceplots and running average plots). Report your findings for both traceplots and the running average plots for $\theta$ and the censored values. Do these diagnostic plots suggest that you have run the sampler long enough? Explain. 

(c) (5 points) Give plots of the estimated density of $\theta \mid \cdots$ and $z_9 \mid \cdots$. Be sure to give brief explanations of your results and findings. (Present plots for 10,000 iterations). 

(d) (5 points) Finally, let's suppose that $r=10,a=1,b=100.$ Do the posterior densities in part (c) change for $\theta \mid \cdots$ and $z_9 \mid \cdots?$
 Do the associated posterior densities change when $r=10, a=100,b=1?$ Please provide plots and an explanation to back up your answer.  (Use 10,000 iterations for the Gibbs sampler).