
---
title: "Measuring the Quality of MCMC Output Workshop"
author: "Rebecca C. Steorts"
output: 
     beamer_presentation:
      includes: 
          in_header: custom2.tex
font-size: 8px
---



Bridging the Gap between Theory and Practice
===

How can we best bridge the gap between theory and practice? 


MCMC diagnostics
===

Are there certain MCMC diagnostics (and packages) that are particularly useful in practice in both teaching/research? 

Potential answers
===

- Traceplots:
- Estimated density: 
- Running average plots:
- Autocorrelation: The lag-k autocorrelation is the correlation between every sample and the sample k steps that occurred prior. 
- Effective sample size: an estimate for the number of independent samples (taking into account autocorrelations) generated by the MCMC run. 
- 

One place where most of these diagnostics can be found is using the \texttt{coda} package on \texttt{CRAN}.

Review papers
===

Are review papers available that bridge theory and practice? 

Answer
===

\url{http://sbfnk.github.io/mfiidd/external_ref/Cowles96_MCMCconvergence.pdf}




