---
title: 'Homework 7 (Lab 9)'
author: "STA-360-602"
output: pdf_document
indent: true
documentclass: article
---

Total points: 10 (reproducibility) + 30 (Q1) = 40 points.\

**General instructions for homeworks**: Please follow the uploading file instructions according to the syllabus. You will give the commands to answer each question in its own code block, which will also produce plots that will be automatically embedded in the output file. Each answer must be supported by written statements as well as any code used. Your code must be completely reproducible and must compile. 

**Advice**: Start early on the homeworks and it is advised that you not wait until the day of. While the professor and the TA's check emails, they will be answered in the order they are received and last minute help will not be given unless we happen to be free.  

**Commenting code**
Code should be commented. See the Google style guide for questions regarding commenting or how to write 
code \url{https://google.github.io/styleguide/Rguide.xml}. No late homework's will be accepted.\

Please look over the homework before lab this week. TA's will answer questions on the homework this week regarding these two 
problems below. I recommend that you work through them as much as possible before lab this week.

1. (Multivariate Normal, 30 points, 10 points each) Hoff exercise 7.3 (Australian crab data).

Question for part b.): What type of plot are we supposed to make here? Are we supposed to make a scatter plot of theta_1 vs theta_2 for each crab type, or a traceplot/running average plot/histogram of posterior values? Are we plotting the two theta values for orange and blue crabs or are we just plotting the average rear width vs. average body depth based on observational data (i.e. just plot the points in the given data set)?

Answer: You want to plot the average rear width (y-axis) versus the average body depth (x-axis) for the orange and blue crabs. That is, you want to plot a whole bunch of posterior samples of the theta values, both for orange and blue crabs. You are NOT plotting the average rear width vs. average body depth based on observational data (i.e. just plot the points in the given data set). 


2. (Imputation, 50 points, 10 points each) Hoff 7.4 (Marriage data), **This is left as an optional exercise that will not be graded.**